### PR TITLE
Create namespace kis and deploy operator in the namespace

### PR DESCRIPTION
**Pull request by hbinkim**
- merge role.yaml, role_binding.yaml, service_account.yaml into single yaml file, common.yaml
- resolves: #20

### CODE REVIEW

**Comment by hbinkim** [comment]
Maybe we can also merge all crd yaml files into common.yaml as well like rook-ceph project does?

- deploy/crds/hypercloud.tmaxanc.com_virtualmachineimages_crd.yaml
- deploy/crds/hypercloud.tmaxanc.com_virtualmachinevolumes_crd.yaml
- deploy/crds/hypercloud.tmaxanc.com_virtualmachinevolumeexports_crd.yaml

**Comment by woohhan** [comment]
> Maybe we can also merge all crd yaml files into common.yaml as well like rook-ceph project does?
> 
> * deploy/crds/hypercloud.tmaxanc.com_virtualmachineimages_crd.yaml
> * deploy/crds/hypercloud.tmaxanc.com_virtualmachinevolumes_crd.yaml
> * deploy/crds/hypercloud.tmaxanc.com_virtualmachinevolumeexports_crd.yaml

@hbinkim The crd files are generated by operator SDK. If the type(vmi, vmv, vme) is changed, does crd files are changed?

**Comment by woohhan** [comment]
we failed e2e test also @hbinkim

**Comment by hbinkim** [comment]
> The crd files are generated by operator SDK. If the type(vmi, vmv, vme) is changed, does crd files are changed?

ah right that's correct.

**Pull request merged**
